import Head from "next/head";
import JobList from "../components/JobList/JobList";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Job List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <JobList />
    </div>
  );
}
